### ISSUE TITLE
Create Button component

### ISSUE THREAD

**Issue by breadadams** [wombak/www#1]
* [x] Depends on #5

[Zeplin](https://app.zeplin.io/project/5e76a2aae68a5e6f93af1053/styleguide/components?cseid=5e778ced90d9966e42dabfae)

![image](https://user-images.githubusercontent.com/5795227/77260470-83c06e80-6c88-11ea-942d-e48f495b6bd5.png)

**Comment by gabrielperales** [comment]
@breadadams Any hover or active effect?
